//更新日志模板
export const UPDATE_TEMPLATE_APP = 'UPDATE_TEMPLATE_APP';
export const UPDATE_TEMPLATE_WEB = 'UPDATE_TEMPLATE_WEB';

//清空日志模板
export const REMOVE_TEMPLATE_APP = 'REMOVE_TEMPLATE_APP';
export const REMOVE_TEMPLATE_WEB = 'REMOVE_TEMPLATE_WEB';
